### ISSUE TITLE
Getting requests.exceptions.HTTPError: 400 Client Error: Bad Request exception

### ISSUE THREAD

**Issue by gyerli** [seemethere/nba_py#16] opened 2016-02-13 15:28 UTC
It is b/c invalid referrer. Possible solution is to add a user agent and referrer to request header. e.g.

headers = {'User-agent': 'Mozilla/5.0', 'referer': 'http://stats.nba.com/scores/'}

**Comment by mcdallas** [comment] 2016-02-13 21:25
it's because of the user-agent not the referer. It was fixed a few days a go but I think it's not up in pypi yet. You might want to try to clone the repo instead.

**Comment by mcdallas** [comment] 2016-02-14 00:27
Actually you are right it is the referer.

**Comment by rymc9384** [comment] 2016-02-24 23:32
There are also issues with the TeamList and Player functions. They seem to be due to the '_endpoint' definitions in the classes. For the TeamList class, the true URL doesn't have the forward slash after 'commonteamyears'. I tried hard coding in the endpoint as 'commonteamyears?&LeagueID=00', but then the issue is the forward slash at the end of the request. 
The link to the JSON file for the TeamList class should be: 'http://stats.nba.com/stats/commonteamyears?&LeagueID=00'. 

I believe that removing the final '/' from the 'BASE_URL' constant in the _init_.py should fix this, but I'm not sure of the repercussions on the rest of the functions.

**Comment by pawelad** [comment] 2016-03-02 23:05
+1, but it seems to be fixed in git master branch.
For now, you can install it directly from git, instead of  PyPI `v0.1a1` version, with `pip install git+https://github.com/seemethere/nba_py.git` command.

**Comment by rymc9384** [comment] 2016-03-03 00:13
Yeah, I created a pull request with it fixed and _seemethere_ merged it in. Thanks for the github install method!

**Comment by siebenecka** [comment] 2016-03-15 01:59
Hello, I am very new to all of this and attempting to utilize this. I am running into a similar issue and was wondering if someone could give some details on how I could fix the problem? I installed the api using the pip command and I have all of that, but I am receiving the same "requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://stats.nba.com/stats/playergamelog?Season=2015-16&SeasonType=Regular+Season&PlayerID=2744&LeagueID=00" error when trying any of the examples and my own. However, when I click the link in the error it takes me to a page filled with the requested stats. Any help would be much appreciated.

**Comment by pawelad** [comment] 2016-03-15 12:10
@siebenecka Did you install it via `pip install git+https://github.com/seemethere/nba_py.git` command? Could you share the code that you're using?

**Comment by siebenecka** [comment] 2016-03-15 14:00
Oh my, I had to reinstall git and allow it to use command prompt...now it works after uninstalling the api and reinstalling with that command! Now I just need to mess around with it and get what I need, thanks for the help!

**Comment by pawelad** [comment] 2016-03-15 14:05
Awesome - [here's](https://github.com/pawelad/nba-rank/blob/master/src/players/management/commands/update_players.py#L25) my usage if anyone's interested.

**Comment by seemethere** [comment] 2016-03-15 19:23
Awesome usage @pawelad! I'll add it to a list of cool things made with nba_py!

**Comment by pawelad** [comment] 2016-03-15 19:33
Awesome library @seemethere ; - )
Thanks, I've actually been kicking the idea for some time, but seeing your library made me finally sit down and do it : )
And let me know if/when you'll need help with something `nba_py` related. For example I've been thinking about creating a PR with player's photo URL's, but wasn't sure if it's a bit 'beyond' NBA Stats API.

**Comment by seemethere** [comment] 2016-03-15 21:26
No if you have a good idea let it fly!

**Closed** 2016-03-15 21:26 UTC
